dependdrop/dependapp/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('', views.index, name='index'),

    path('templates/register', views.register, name="register"),
    path('templates/login', views.loginpage, name="login"),
    path('templates/formpage', views.person_create_view, name='formpage'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

    # path('template/formpage', views.Userform, name="Userform"),

    path('templates/logout', views.logout, name="logout"),

     # AJAX
]

dependdrop/dependdrop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dependapp.urls'))
]

dependdrop/dependapp/models.py
from django.db import models

# Create your models here.
from django.db import models


class Districts(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Branches(models.Model):
    district = models.ForeignKey(Districts, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Person(models.Model):

    district = models.ForeignKey(Districts, on_delete=models.SET_NULL, blank=True, null=True)
    branch = models.ForeignKey(Branches, on_delete=models.SET_NULL, blank=True, null=True)

dependdrop/dependapp/forms.py
from django import forms

from .models import Person, Branches


class PersonCreationForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branches.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['branch'].queryset = Branches.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.district.branch_set.order_by('name')

dependdrop/dependapp/views.py
from django.contrib import auth, messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404

from .forms import PersonCreationForm
from .models import Person, Branches


def index(request):
    return render(request, "index.html")


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Successfully Registered")
            return render(request, 'login.html')
    else:

        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'register.html', context)


def loginpage(request):
    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('formpage')
        else:
            messages.info(request, 'username or password incorrect')
            return render(request, 'login.html')

    return render(request, 'login.html')


def person_create_view(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Application accepted", )
            return redirect('/')
    return render(request, 'formpage.html', {'form': form})


# def Userform(request):
#     form = PersonCreationForm()
#     if request.method == 'POST':
#         form = PersonCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, "Successfully Registered", )
#             return redirect('/')
#     return render(request, 'formpage.html', {'form': form})


def load_cities(request):
    district_id = request.GET.get('district_id')
    branches = Branches.objects.filter(district_id=district_id).all()
    return render(request, 'city_dropdown_list_options.html', {'branches': branches})

    # return JsonResponse(list(cities.values('id', 'name')), safe=False)


def logout(request):
    auth.logout(request)
    return redirect('/')

dependdrop/templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

dependdrop/templates/formpage.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
</head>
<style>
#myDIV {
display:none;
  width: 100%;
  padding: 50px 0;
  text-align: center;
  background-color: lightblue;
  margin-top: 20px;
}
#success-message {
    display: none;
}
#success-message.show {
    display: block;
}
.success_text {
    text-align: center;
    font-weight: bold;
}
</style>
<body>
<button onclick="myFunction()">OPEN FORM</button>

<div id="myDIV">
 <div class="user_card">
     <h2>Person Form</h2>

    <table>
        <tr>
    <td><label>Name:</label></td>
    <td><input type="text" name="username" id="username" placeholder="your name" required></td>
  </tr>
    <tr>
    <td><label for="email">Email:</label></td>
    <td><input type="text" name="email" id="email" placeholder="your email" required></td>
  </tr>
  <tr>
    <td><label for="dob">DOB:</label></td>
    <td><input type="date" name="dob" id="dob" placeholder="DOB"></td>
  </tr>
  <tr>
    <td><label >Age:</label></td>
    <td><input type="number" name="number" id="number" placeholder="Age"></td>
  </tr>
  <tr>
    <td><label>Gender:</label></td>
    <td>Male: <input type="radio" name="gender" value="male">
      Female: <input type="radio" name="gender" value="female">

  </tr>
  <tr>
    <td><label for="phoneNumber">Phone Number:</label></td>
    <td><input type="number" name="phoneNumber" id="phoneNumber"></td>
  </tr>

  <tr>
    <td><label for="password">Password:</label></td>
    <td><input type="password" name="password" id="password"></td>
  </tr>
  <tr>
    <td><label for="address">Address:</label></td>
    <td><textarea name="address" id="address" placeholder="Address"></textarea></td>
  </tr>
        <tr>
    <td><label for="Account">Account Type</label></td>
    <td>
      <select id="account" name="account">
        <option value="">Choose</option>
        <option value="Savings">Savings</option>
        <option value="Current">Current</option>
      </select></td>
  </tr>
  <tr>
    <td><label>Materials Required :</label></td>
    <td>
      <input type="checkbox" id="debit" name="materials[]" value="Debit Card">
      <label for="debit">Debit Card</label>
      <input type="checkbox" id="credit" name="materials[]" value="Credit Card">
      <label for="credit">Credit Card</label>
      <input type="checkbox" id="cheque" name="materials[]" value="Chequebook">
      <label for="debit">Cheque Book</label>
    </td>
  </tr>

    </table>
             <form method="POST"  id="personForm"  data-branches-url="{% url 'ajax_load_cities' %}">
        {% csrf_token %}
       {{ form.as_p }}
      <input type="submit" value="Submit">
        {% for msg in messages %}
				           <h6> {{msg}}</h6><br>
        	                   {% endfor %}
       <li><a class="links" href="logout">LOGOUT</a></li>


</form>

 </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
        const url = $("#personForm").attr("data-branches-url"); 
        const districtId = $(this).val();

        $.ajax({                       
            url: url,                    
            data: {
                'district_id': districtId       
            },
            success: function (data) {   
                $("#id_branch").html(data);  
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (branch) {
                    html_data += `<option value="${branch.id}">${branch.name}</option>`
                });
                console.log(html_data);
                $("#id_branch").html(html_data);

                */
            }
        });

    });
</script>
 <script>
function myFunction() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
};
</script>

</body>
</html>

dependdrop/templates/index.html
<!DOCTYPE html>
<!-- Created By CodingNepal - www.codingnepalweb.com -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
   <!-- <title> Responsive Drop Down Navigation Menu | CodingLab </title>-->
    <link rel="stylesheet" href="style.css">
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
<style>

*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
body{
  min-height: 100vh;
}
nav{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  height: 70px;
  background: #3E8DA8;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
  z-index: 99;
}
nav .navbar{
  height: 100%;
  max-width: 1250px;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin: auto;
  /* background: red; */
  padding: 0 50px;
}
.navbar .logo a{
  font-size: 30px;
  color: #fff;
  text-decoration: none;
  font-weight: 600;
}
nav .navbar .nav-links{
  line-height: 70px;
  height: 100%;
}
nav .navbar .links{
  display: flex;
}
nav .navbar .links li{
  position: relative;
  display: flex;
  align-items: center;
  justify-content: space-between;
  list-style: none;
  padding: 0 14px;
}
nav .navbar .links li a{
  height: 100%;
  text-decoration: none;
  white-space: nowrap;
  color: #fff;
  font-size: 15px;
  font-weight: 500;
}
.links li:hover .htmlcss-arrow,
.links li:hover .js-arrow{
  transform: rotate(180deg);
  }

nav .navbar .links li .arrow{
  /* background: red; */
  height: 100%;
  width: 22px;
  line-height: 70px;
  text-align: center;
  display: inline-block;
  color: #fff;
  transition: all 0.3s ease;
}
nav .navbar .links li .sub-menu{
  position: absolute;
  top: 70px;
  left: 0;
  line-height: 40px;
  background: #3E8DA8;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
  border-radius: 0 0 4px 4px;
  display: none;
  z-index: 2;
}
nav .navbar .links li:hover .htmlCss-sub-menu,
nav .navbar .links li:hover .js-sub-menu{
  display: block;
}
.navbar .links li .sub-menu li{
  padding: 0 22px;
  border-bottom: 1px solid rgba(255,255,255,0.1);
}
.navbar .links li .sub-menu a{
  color: #fff;
  font-size: 15px;
  font-weight: 500;
}
.navbar .links li .sub-menu .more-arrow{
  line-height: 40px;
}
.navbar .links li .htmlCss-more-sub-menu{
  /* line-height: 40px; */
}
.navbar .links li .sub-menu .more-sub-menu{
  position: absolute;
  top: 0;
  left: 100%;
  border-radius: 0 4px 4px 4px;
  z-index: 1;
  display: none;
}
.links li .sub-menu .more:hover .more-sub-menu{
  display: block;
}
.navbar .search-box{
  position: relative;
   height: 40px;
  width: 40px;
}
.navbar .search-box i{
  position: absolute;
  height: 100%;
  width: 100%;
  line-height: 40px;
  text-align: center;
  font-size: 22px;
  color: #fff;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
}
.navbar .search-box .input-box{
  position: absolute;
  right: calc(100% - 40px);
  top: 80px;
  height: 60px;
  width: 300px;
  background: #3E8DA8;
  border-radius: 6px;
  opacity: 0;
  pointer-events: none;
  transition: all 0.4s ease;
}
.navbar.showInput .search-box .input-box{
  top: 65px;
  opacity: 1;
  pointer-events: auto;
  background: #3E8DA8;
}
.search-box .input-box::before{
  content: '';
  position: absolute;
  height: 20px;
  width: 20px;
  background: #3E8DA8;
  right: 10px;
  top: -6px;
  transform: rotate(45deg);
}
.search-box .input-box input{
  position: absolute;
  top: 50%;
  left: 50%;
  border-radius: 4px;
  transform: translate(-50%, -50%);
  height: 35px;
  width: 280px;
  outline: none;
  padding: 0 15px;
  font-size: 16px;
  border: none;
}
.navbar .nav-links .sidebar-logo{
  display: none;
}
.navbar .bx-menu{
  display: none;
}
@media (max-width:920px) {
  nav .navbar{
    max-width: 100%;
    padding: 0 25px;
  }

  nav .navbar .logo a{
    font-size: 27px;
  }
  nav .navbar .links li{
    padding: 0 10px;
    white-space: nowrap;
  }
  nav .navbar .links li a{
    font-size: 15px;
  }
}
@media (max-width:800px){
  nav{
    /* position: relative; */
  }
  .navbar .bx-menu{
    display: block;
  }
  nav .navbar .nav-links{
    position: fixed;
    top: 0;
    left: -100%;
    display: block;
    max-width: 270px;
    width: 100%;
    background:  #3E8DA8;
    line-height: 40px;
    padding: 20px;
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
    transition: all 0.5s ease;
    z-index: 1000;
  }
  .navbar .nav-links .sidebar-logo{
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
  .sidebar-logo .logo-name{
    font-size: 25px;
    color: #fff;
  }
    .sidebar-logo  i,
    .navbar .bx-menu{
      font-size: 25px;
      color: #fff;
    }
  nav .navbar .links{
    display: block;
    margin-top: 20px;
  }
  nav .navbar .links li .arrow{
    line-height: 40px;
  }
nav .navbar .links li{
    display: block;
  }
nav .navbar .links li .sub-menu{
  position: relative;
  top: 0;
  box-shadow: none;
  display: none;
}
nav .navbar .links li .sub-menu li{
  border-bottom: none;

}
.navbar .links li .sub-menu .more-sub-menu{
  display: none;
  position: relative;
  left: 0;
}
.navbar .links li .sub-menu .more-sub-menu li{
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.links li:hover .htmlcss-arrow,
.links li:hover .js-arrow{
  transform: rotate(0deg);
  }
  .navbar .links li .sub-menu .more-sub-menu{
    display: none;
  }
  .navbar .links li .sub-menu .more span{
    /* background: red; */
    display: flex;
    align-items: center;
    /* justify-content: space-between; */
  }

  .links li .sub-menu .more:hover .more-sub-menu{
    display: none;
  }
  nav .navbar .links li:hover .htmlCss-sub-menu,
  nav .navbar .links li:hover .js-sub-menu{
    display: none;
  }
.navbar .nav-links.show1 .links .htmlCss-sub-menu,
  .navbar .nav-links.show3 .links .js-sub-menu,
  .navbar .nav-links.show2 .links .more .more-sub-menu{
      display: block;
    }
    .navbar .nav-links.show1 .links .htmlcss-arrow,
    .navbar .nav-links.show3 .links .js-arrow{
        transform: rotate(180deg);
}
    .navbar .nav-links.show2 .links .more-arrow{
      transform: rotate(90deg);
    }
}
@media (max-width:370px){
  nav .navbar .nav-links{
  max-width: 100%;
}
}
</style>


    <nav>
    <div class="navbar">
      <i class='bx bx-menu'></i>
      <div class="logo">ONLINE BANKING</a></div>
      <div class="nav-links">
        <div class="sidebar-logo">
          <span class="logo-name">onlinebanking</span>
          <i class='bx bx-x' ></i>
        </div>
        <ul class="links">
          <li>HOME</li>

          <li>
            <a href="#">DISTRICTS</a>
            <i class='bx bxs-chevron-down js-arrow arrow '></i>
            <ul class="js-sub-menu sub-menu">
              <li>  <a class="links" href="https://en.wikipedia.org/wiki/Kozhikode">CALICUT</a></li>
              <li><a class="links" href="https://en.wikipedia.org/wiki/malappuram">MALAPPURAM</a></li>
              <li>     <a class="links" href="https://en.wikipedia.org/wiki/Alappuzha">ALAPPUYA</a></li>
              <li><a class="links" href="https://en.wikipedia.org/wiki/Kannur">KANNUR</a></li>
              <li><a class="links" href="https://en.wikipedia.org/wiki/palakkad">PALAKKAD</a></li>
            </ul>
          </li>
          <li><a href="templates/register">REGISTER</a></li>
          <li><a href="templates/login">LOGIN</a></li>
        </ul>
      </div>
      <div class="search-box">
        <i class='bx bx-search'></i>
        <div class="input-box">
          <input type="text" placeholder="Search...">
        </div>
      </div>
    </div>
    <div>
<!--          <a href="template/login">-->
    <button>click here</button>
  </a>
    </div>
  </nav>


</body>
</html>

dependdrop/templates/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background:LightSeaGreen  !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
		    background-color:Tomato;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 30px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
			}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">

				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="login">
                        {% csrf_token %}

						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>
                            {% for msg in messages %}
				           <h6> {{msg}}</h6><br>
        	                   {% endfor %}
                             <div class="mt-4">
					          <div class="d-flex justify-content-center links">
						       <button type="submit">LOGIN</button>
					          </div>
				          </div>

                       </form>
                    </div>



				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="register" class="ml-2">REGISTER</a>

					</div>

				</div>



		</div>
	</div>
	</div>

</body>

</html>

dependdrop/templates/register.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: LightSeaGreen !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: Tomato;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 30px;
		}

		#form-title{
			color: white;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}


	</style>

</head>
<body>

	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="register">
						{% csrf_token %}


                         {% for field in form %}
                         <div>
                          <p>{{ field.label }}: <br> {{ field }}</p>

            {% for error in field.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        </div>
    {% endfor %}
    {% for msg in messages %}
				<h2> {{msg}}</h2>
        	{% endfor %}
    <button type="submit">Register</button>
</form>
				</div>


			</div>
		</div>
	</div>


</body>
</html>